apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: http://backstage.io
spec:
  type: library
  owner: CNCF
  lifecycle: production
